[package]
name = "interfaces"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.0"

[dependencies]
libloading = "0.8.6"
serde = { version = "1.0.215", features = ["derive"] }
serde_yml = "0.0.12"


[lib]
name = "interfaces"
path = "src/lib.rs"